### ISSUE TITLE
Release Chores

### ISSUE THREAD

**Issue by Nemo157** [Nemo157/prom-attire-rs#2]
- [x] Cargo.toml Metadata (description, repository url, keywords, categories, license, etc.)
 - [ ] Examples
 - [x] Travis CI (tests (w/ `--all` for workspace), rustfmt, clippy)
 - [x] Name (#1)

**Comment by TedDriggs** [comment]
Would you be open to PRs on these to move towards getting v0.1.0 up on crates.io? @colin-kiegel and I are interested in this for [`derive_builder`](https://github.com/colin-kiegel/rust-derive-builder), but we'd need it to be published.

**Comment by Nemo157** [comment]
I can get the metadata and Travis CI setup super quick. For the examples I'm not sure what the nicest way to document `proc_macro` crates is, but I can just add a simple example for now and work on improving the documentation after the initial release. So I think I can get a 0.1 published today for you to take a look at 😄

**Comment by Nemo157** [comment]
Metadata done and Travis CI setup. A single example is in the docs and I've opened #5 for adding examples for the rest. I'll tag 0.1.0 now and hopefully Travis will successfully publish soon.
